### ISSUE TITLE
Upgrading enzyme (required for react 16 update)

### ISSUE THREAD

**Issue by jparkrr** [MoveOnOrg/mop-frontend#505]
Here are some issues I had running tests after upgrading enzyme:

```
     TypeError: Cannot read property '_instance' of undefined
      at unwrapReduxComponent (test/lib.js:10:3)

     Error:
        Attempted to access ReactWrapper::node, which was previously a private property on
        Enzyme ReactWrapper instances, but is no longer and should not be relied upon.
        Consider using the getElement() method instead.

      at ReactWrapper.get (node_modules/enzyme/build/ReactWrapper.js:1689:15)
      at Context.<anonymous> (test/pages/forgot-password.js:30:5)

     Warning: <stateValidationError /> is using incorrect casing. Use PascalCase for React components, or   
     lowercase for HTML elements.
     [... Many of these]
```

You can see the branch here, which also includes updating to React 16 and `MoNav` use context https://github.com/MoveOnOrg/mop-frontend/compare/monav-context

**Comment by jparkrr** [comment]
Probably very possible to fix them all, I just didn't want to spend too much time on it right now. Let me know if you want me to take it up.

**Comment by jparkrr** [comment]
Figured it out in #509
